#!/bin/bash
#SBATCH --job-name="gfort_mpi"
#SBATCH --output="%x.%j.%N.out"
#SBATCH --partition=gpu-shared
#SBATCH --gpus=2
#SBATCH --nodes=1
#SBATCH --ntasks=2
#SBATCH --no-requeue
#SBATCH --mem=20G
#SBATCH --account=TG-DMR180071
#SBATCH -t 01:00:00

module purge
module load slurm
module load gpu
module load intel/19.1.3.304
module load intel-mkl/2020.4.304
module load intel-mpi/2019.10.317/uwgziob
#module load cuda11.7/toolkit
#module load cuda11.7/blas
#module load nvhpc/21.9
#export LD_LIBRARY_PATH=/cm/shared/apps/spack/0.17.3/gpu/b/opt/spack/linux-rocky8-skylake_avx512/gcc-8.5.0/nvhpc-21.9-4xco23dnhjhodonoufuduj4obaewort7/Linux_x86_64/21.9/compilers/lib:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=/cm/shared/apps/spack/0.17.3/gpu/b/opt/spack/linux-rocky8-skylake_avx512/gcc-8.5.0/nvhpc-21.9-4xco23dnhjhodonoufuduj4obaewort7/Linux_x86_64/21.9/cuda/lib64/:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=/cm/shared/apps/spack/0.17.3/gpu/b/opt/spack/linux-rocky8-skylake_avx512/gcc-8.5.0/nvhpc-21.9-4xco23dnhjhodonoufuduj4obaewort7/Linux_x86_64/21.9/math_libs/lib64/:$LD_LIBRARY_PATH
#
# . /home/zliu12/.env.nvhpc_intel
#Load module file(s) into the shell environment

QEBIN=/home/zliu12/software/qe-7.3/bin/
PW=$QEBIN/pw.x
PH=$QEBIN/ph.x
# export I_MPI_PMI_LIBRARY=pmix
nvidia-smi

./deviceQueryDrv

which mpirun >> mpirun.execs

#mpirun -np 2 $PW < scf_epw.in > scf.out
#mpirun -np 2 $PW < nscf_epw.in > nscf.out
mpirun -np 2 ./test.x
